default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: jmjny383
  host: 127.0.0.1
  port: 5432
  pool: 5

production:
  <<: *default
  database: breaking_production

development:
  <<: *default
  database: breaking_development

test:
  <<: *default
  database: breaking_test